CadastroDeContatos/Controllers/AlterarSenhaController.cs
using System;
using CadastroDeContatos.Helper;
using CadastroDeContatos.Models;
using CadastroDeContatos.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace CadastroDeContatos.Controllers
{
    public class AlterarSenhaController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly ISessao _sessao;
        public AlterarSenhaController(IUserRepository userRepository, ISessao sessao)
        {
            _userRepository = userRepository;
            _sessao = sessao;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Alterar(AlterarSenhaModel alterarSenhaModel)
        {
            try
            {

                UserModel usuario = _sessao.BuscarSessao();
                alterarSenhaModel.Id = usuario.Id;

                if (ModelState.IsValid)
                {
                    _userRepository.AlterarSenha(alterarSenhaModel);
                    TempData["MensagemSucesso"] = "Senha alterada com sucesso!";
                    _sessao.RemoverSessao();
                    return RedirectToAction("Index", "Login");
                }
                return View("Index", alterarSenhaModel);
            }
            catch(Exception e)
            {
                TempData["MensagemErro"] = $"Não foi possível redefinir sua senha, por favor verifique os campos enviados, detalhe do erro: {e.Message}";
                return View("Index", alterarSenhaModel);
            }
        }
    }
}

CadastroDeContatos/Views/AlterarSenha/Index.cshtml
@model AlterarSenhaModel
@{
    Layout = "_Layout";
    ViewData["Title"] = "Alterar senha";
}
@if (TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-outline-danger btn-sm close-alert">X</button>
        @TempData["MensagemErro"]
    </div>
}

@if (TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-outline-danger btn-sm close-alert">X</button>
        @TempData["MensagemSucesso"]
    </div>

}
<div class="login">

    <form asp-controller="AlterarSenha" asp-action="Alterar" method="post" class="form-login">

        <h1>Alterar senha</h1>

        <div class="form-group">
            <label for="senha-atual">Senha atual</label>
            <input type="password" asp-for="SenhaAtual" class="form-control" placeholder="Digite sua senha atual">
            @Html.ValidationMessageFor(x => x.SenhaAtual)
        </div>

        <div class="form-group">
            <label for="senha-nova">Nova senha</label>
            <input type="password" asp-for="NovaSenha" class="form-control" placeholder="Digite sua nova senha">
            @Html.ValidationMessageFor(x => x.NovaSenha)
        </div>

        <div class="form-group">
            <label for="confirma">Confirmar senha</label>
            <input type="password" asp-for="ConfirmarNovaSenha" class="form-control" placeholder="Confirme sua senha">
            @Html.ValidationMessageFor(x => x.ConfirmarNovaSenha)
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
		<a role="button" class="btn btn-secondary" asp-controller="Home" asp-action="index">Voltar</a>

    </form>
</div>