CadastroDeContatos/Controllers/ContatoController.cs
using System.Collections.Generic;
using CadastroDeContatos.Filters;
using CadastroDeContatos.Helper;
using CadastroDeContatos.Models;
using CadastroDeContatos.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace CadastroDeContatos.Controllers
{
    [PaginaUserLogado]
    public class ContatoController : Controller
    {

        private readonly IContatoRepository _contatoRepository;
        private readonly ISessao _sessao;

        public ContatoController(IContatoRepository contatoRepository, ISessao sessao)
        {
            _contatoRepository = contatoRepository;
            _sessao = sessao;
        }
        public IActionResult Index()
        {
            UserModel usuario = _sessao.BuscarSessao();
            List<ContatoModel> contatos = _contatoRepository.BuscarTodos(usuario.Id);
            return View(contatos);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int Id)
        {
            var contato = _contatoRepository.BuscarPorId(Id);
            return View(contato);
        }

        public IActionResult ApagarConfirmacao(int Id)
        {
            var contato = _contatoRepository.BuscarPorId(Id);
            return View(contato);
        }

        public IActionResult Apagar(int Id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _contatoRepository.Apagar(Id);
                    TempData["MensagemSucesso"] = "Contato excluido com sucesso";
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Index");
            }
            catch (System.Exception e)
            {
                TempData["MensagemErro"] = $"Não foi possível excluir o contato: ${e.Message}";
                return RedirectToAction("Index");
            }
            
        }

        [HttpPost]
        public IActionResult Criar(ContatoModel contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UserModel usuario = _sessao.BuscarSessao();
                    contato.UsuarioId = usuario.Id;
                    _contatoRepository.Adicionar(contato);
                    TempData["MensagemSucesso"] = "Contato salvo com sucesso";
                    return RedirectToAction("Index");
                }
                return View(contato);
            }
            catch(System.Exception e)
            {
                TempData["MensagemErro"] = $"Não foi possível cadastrar o contato: ${e.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Editar(ContatoModel contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _contatoRepository.Editar(contato);
                    TempData["MensagemSucesso"] = "Contato editado com sucesso";
                    return RedirectToAction("Index");
                }
                return View(contato);
            }
            catch(System.Exception e)
            {
                TempData["MensagemErro"] = $"Não foi possível Editar o usuário: ${e.Message}";
                return RedirectToAction("Index");
            }
            
        }


    }
}

CadastroDeContatos/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using CadastroDeContatos.Filters;
using CadastroDeContatos.Models;
using CadastroDeContatos.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace CadastroDeContatos.Controllers
{
    [PaginaRestrita] 
    public class UserController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly IContatoRepository _contatoRepository;
        public UserController(IUserRepository userRepository, IContatoRepository contatoRepository)
        {
            _userRepository = userRepository;
            _contatoRepository = contatoRepository;
        }
        public IActionResult Index()
        {
            List<UserModel> usuarios = _userRepository.BuscarTodos();
            return View(usuarios);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult ApagarConfirmacao(int Id)
        {
            UserModel usuario = _userRepository.BuscarPorId(Id);
            return View(usuario);
        }
        public IActionResult Editar(int Id)
        {
            UserModel usuario = _userRepository.BuscarPorId(Id);
            return View(usuario);
        }

        public IActionResult ListarContatoPorUsuarioId(int UsuarioId)
        {

            List<ContatoModel> contatos = _contatoRepository.BuscarTodos(UsuarioId);

            return PartialView("_ContatosUsuario", contatos);
        }

        [HttpPost]
        public IActionResult Criar(UserModel usuario)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _userRepository.Adicionar(usuario);
                    TempData["MensagemSucesso"] = "Usuario cadastrado com sucesso";
                    return RedirectToAction("Index");
                }
                return View(usuario);
            }
            catch (Exception e)
            {
                TempData["MensagemErro"] = $"Não foi possível cadastrar o usuário: ${e.Message}";
                return RedirectToAction("Index");
            }
        }

        public IActionResult Apagar(int id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _userRepository.Apagar(id);
                    TempData["MensagemSucesso"] = "Usuario excluido com sucesso";
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                TempData["MensagemErro"] = $"Não foi possível excluir o usuário: ${e.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Editar(UserSemSenhaModel usuarioSemSenha)
        {
            try
            {
                UserModel usuario = null;
                if (ModelState.IsValid)
                {
                    usuario = new UserModel() { 

                        Id = usuarioSemSenha.Id,
                        Nome = usuarioSemSenha.Nome,
                        Login = usuarioSemSenha.Login,
                        Email = usuarioSemSenha.Email,
                        Perfil = usuarioSemSenha.Perfil
                    };

                    usuario = _userRepository.Editar(usuario);
                    TempData["MensagemSucesso"] = "Usuário editado com sucesso";
                    return RedirectToAction("Index");
                }
                return View(usuario);
            }
            catch (Exception e)
            {
                TempData["MensagemErro"] = $"Não foi possível Editar o usuário: ${e.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

CadastroDeContatos/Views/Contato/ApagarConfirmacao.cshtml
@model ContatoModel
@{
	ViewData["Title"] = "Apagar contato";
}

<div class="text-center">
	<h3>Deseja realmente apagar (@Model.Nome)?</h3>


	<a class="btn btn-primary" role="button" asp-controller="Contato" asp-action="index">Cancelar exclusão</a>
	<a class="btn btn-danger" role="button" asp-controller="Contato" asp-action="apagar" asp-route-id="@Model.Id">Confirmar exclusão</a>
</div>

CadastroDeContatos/Views/Contato/Criar.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Criar contato";
}


<div class="text-center">
    <h1 class="display-4">Criar contato</h1>
</div>

<form asp-controller="Contato" asp-action="Criar" method="post">

    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control"placeholder="Digite o nome do contato">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="form-group">
        <label for="email">Email</label>
        <input type="email"  asp-for="Email" class="form-control" placeholder="Digite o email do contato">
        @Html.ValidationMessageFor(x => x.Email)
    </div>

    <div class="form-group">
        <label for="celular">Celular</label>
        <input type="text" asp-for="Celular" class="form-control" placeholder="Digite o celular do contato">
        @Html.ValidationMessageFor(x => x.Celular)
    </div>


    <button type="submit" class="btn btn-primary">Submit</button>
     <a role="button" class="btn btn-secondary" asp-controller="Contato" asp-action="index">Voltar</a>
</form>

CadastroDeContatos/Views/Contato/Editar.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Editar contato";
}


<div class="text-center">
    <h1 class="display-4">Editar contato</h1>
</div>

<form asp-controller="Contato" asp-action="editar" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" asp-for="Email" class="form-control">
        @Html.ValidationMessageFor(x => x.Email)
    </div>

    <div class="form-group">
        <label for="celular">Celular</label>
        <input type="text" asp-for="Celular" class="form-control">
        @Html.ValidationMessageFor(x => x.Celular)
    </div>


    <button type="submit" class="btn btn-primary">Submit</button>
    <a role="button" class="btn btn-secondary" asp-controller="User" asp-action="index">Voltar</a>
</form>

CadastroDeContatos/Views/Contato/Index.cshtml
@model List<ContatoModel>
@{
    ViewData["Title"] = "Listagem de Contatos";		
}

<div class="text-center">
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a role="button" class="btn btn-success" asp-controller="Contato" asp-action="Criar">Adicionar contato</a>
    </div>

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-outline-danger btn-sm close-alert">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }
    
    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-outline-danger btn-sm close-alert">X</button>
            @TempData["MensagemErro"]
        </div>
    }
    <h1 class="display-4">Listagem de contatos</h1>

    <table class="table" id="tabelaContatos">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Email</th>
                <th scope="col">Celular</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if(Model != null && Model.Any())
            {
                foreach(var item in Model)
                {
                    <tr>
                        <th scope="row">@item.Id</th>
                        <td>@item.Nome</td>
                        <td>@item.Email</td>
                        <td>@item.Celular</td>
                        <td>
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <a role="button" class="btn btn-primary" asp-route-id="@item.Id" asp-controller="Contato" asp-action="editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@item.Id" asp-controller="Contato" asp-action="apagarConfirmacao">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>